// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolAPI.Persistence.EF;

namespace SchoolAPI.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20210822040240_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Credits")
                        .HasColumnType("int")
                        .HasColumnName("credits");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("CourseID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            Credits = 2000000,
                            DepartmentID = 7,
                            Title = "Thiet ke mau"
                        },
                        new
                        {
                            CourseID = 2,
                            Credits = 3000000,
                            DepartmentID = 2,
                            Title = "Giao duc the chat"
                        },
                        new
                        {
                            CourseID = 3,
                            Credits = 4000000,
                            DepartmentID = 3,
                            Title = "Quoc phong"
                        },
                        new
                        {
                            CourseID = 4,
                            Credits = 5000000,
                            DepartmentID = 7,
                            Title = "Thiet ke web"
                        },
                        new
                        {
                            CourseID = 5,
                            Credits = 5000000,
                            DepartmentID = 7,
                            Title = "Quan tri co so du lieu"
                        });
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.CourseAssignment", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int>("InstructorID")
                        .HasColumnType("int")
                        .HasColumnName("instructor_id");

                    b.HasKey("CourseID", "InstructorID");

                    b.HasIndex("InstructorID");

                    b.ToTable("CourseAssignment");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            InstructorID = 2
                        },
                        new
                        {
                            CourseID = 5,
                            InstructorID = 1
                        },
                        new
                        {
                            CourseID = 3,
                            InstructorID = 2
                        },
                        new
                        {
                            CourseID = 2,
                            InstructorID = 3
                        },
                        new
                        {
                            CourseID = 4,
                            InstructorID = 1
                        });
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal")
                        .HasColumnName("budget");

                    b.Property<int>("InstructorID")
                        .HasColumnType("int")
                        .HasColumnName("instructor_id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.HasKey("DepartmentID");

                    b.HasIndex("InstructorID");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            Budget = 3000000m,
                            InstructorID = 1,
                            Name = "English",
                            StartDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(3796)
                        },
                        new
                        {
                            DepartmentID = 2,
                            Budget = 3000000m,
                            InstructorID = 2,
                            Name = "Computer Science",
                            StartDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(4526)
                        },
                        new
                        {
                            DepartmentID = 3,
                            Budget = 3000000m,
                            InstructorID = 3,
                            Name = "Scince",
                            StartDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(4530)
                        },
                        new
                        {
                            DepartmentID = 4,
                            Budget = 3000000m,
                            InstructorID = 1,
                            Name = "Social Studies",
                            StartDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(4531)
                        },
                        new
                        {
                            DepartmentID = 5,
                            Budget = 3000000m,
                            InstructorID = 2,
                            Name = "Theology",
                            StartDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(4532)
                        },
                        new
                        {
                            DepartmentID = 6,
                            Budget = 3000000m,
                            InstructorID = 3,
                            Name = "Mathematics",
                            StartDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(4534)
                        },
                        new
                        {
                            DepartmentID = 7,
                            Budget = 3000000m,
                            InstructorID = 1,
                            Name = "IT",
                            StartDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(4535)
                        });
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseID")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("grade");

                    b.Property<int>("StudentID")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollment");

                    b.HasData(
                        new
                        {
                            EnrollmentID = 1,
                            CourseID = 2,
                            Grade = "A",
                            StudentID = 1
                        },
                        new
                        {
                            EnrollmentID = 2,
                            CourseID = 3,
                            Grade = "C",
                            StudentID = 1
                        },
                        new
                        {
                            EnrollmentID = 3,
                            CourseID = 4,
                            Grade = "D",
                            StudentID = 2
                        },
                        new
                        {
                            EnrollmentID = 4,
                            CourseID = 5,
                            Grade = "A",
                            StudentID = 2
                        },
                        new
                        {
                            EnrollmentID = 5,
                            CourseID = 1,
                            Grade = "B",
                            StudentID = 3
                        },
                        new
                        {
                            EnrollmentID = 6,
                            CourseID = 2,
                            Grade = "None",
                            StudentID = 3
                        },
                        new
                        {
                            EnrollmentID = 7,
                            CourseID = 4,
                            Grade = "E",
                            StudentID = 3
                        });
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("instructor_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstMidName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_mid_name");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hire_date");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.HasKey("ID");

                    b.ToTable("Instructor");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstMidName = "Son Kim Quang",
                            HireDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(2418),
                            LastName = "Thach"
                        },
                        new
                        {
                            ID = 2,
                            FirstMidName = "Ngoc Tam",
                            HireDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(3058),
                            LastName = "Vo"
                        },
                        new
                        {
                            ID = 3,
                            FirstMidName = "Van A",
                            HireDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(3063),
                            LastName = "Nguyen"
                        },
                        new
                        {
                            ID = 4,
                            FirstMidName = "Thoai",
                            HireDate = new DateTime(2021, 8, 22, 11, 2, 40, 215, DateTimeKind.Local).AddTicks(3065),
                            LastName = "Chi"
                        });
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.OfficeAssignment", b =>
                {
                    b.Property<int>("InstructorID")
                        .HasColumnType("int")
                        .HasColumnName("instructor_id");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("location");

                    b.HasKey("InstructorID");

                    b.ToTable("OfficeAssignment");
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("enrollment_date");

                    b.Property<string>("FirstMidName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_mid_name");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.HasKey("ID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EnrollmentDate = new DateTime(2021, 8, 22, 11, 2, 40, 212, DateTimeKind.Local).AddTicks(7200),
                            FirstMidName = "Nhat Nam",
                            LastName = "Hoang"
                        },
                        new
                        {
                            ID = 2,
                            EnrollmentDate = new DateTime(2021, 8, 22, 11, 2, 40, 214, DateTimeKind.Local).AddTicks(2408),
                            FirstMidName = "Nhat Minh",
                            LastName = "Thi"
                        },
                        new
                        {
                            ID = 3,
                            EnrollmentDate = new DateTime(2021, 8, 22, 11, 2, 40, 214, DateTimeKind.Local).AddTicks(2421),
                            FirstMidName = "Viet Hung",
                            LastName = "Ngo"
                        },
                        new
                        {
                            ID = 4,
                            EnrollmentDate = new DateTime(2021, 8, 22, 11, 2, 40, 214, DateTimeKind.Local).AddTicks(2423),
                            FirstMidName = "Duc Thai",
                            LastName = "Luu"
                        });
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Course", b =>
                {
                    b.HasOne("SchoolAPI.Persistence.Entities.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.CourseAssignment", b =>
                {
                    b.HasOne("SchoolAPI.Persistence.Entities.Course", "Course")
                        .WithMany("CourseAssignment")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Persistence.Entities.Instructor", "Instructor")
                        .WithMany("CourseAssignment")
                        .HasForeignKey("InstructorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Department", b =>
                {
                    b.HasOne("SchoolAPI.Persistence.Entities.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Enrollment", b =>
                {
                    b.HasOne("SchoolAPI.Persistence.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Persistence.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.OfficeAssignment", b =>
                {
                    b.HasOne("SchoolAPI.Persistence.Entities.Instructor", "Instructor")
                        .WithOne("OfficeAssignment")
                        .HasForeignKey("SchoolAPI.Persistence.Entities.OfficeAssignment", "InstructorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Course", b =>
                {
                    b.Navigation("CourseAssignment");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Instructor", b =>
                {
                    b.Navigation("CourseAssignment");

                    b.Navigation("OfficeAssignment");
                });

            modelBuilder.Entity("SchoolAPI.Persistence.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
