// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolAPI.Models;

namespace SchoolAPI.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20210818050029_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolAPI.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            Credits = 2000000,
                            Title = "Thiet ke mau"
                        },
                        new
                        {
                            CourseID = 2,
                            Credits = 3000000,
                            Title = "Giao duc the chat"
                        },
                        new
                        {
                            CourseID = 3,
                            Credits = 4000000,
                            Title = "Quoc phong"
                        },
                        new
                        {
                            CourseID = 4,
                            Credits = 5000000,
                            Title = "Thiet ke web"
                        },
                        new
                        {
                            CourseID = 5,
                            Credits = 5000000,
                            Title = "Quan tri co so du lieu"
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("SchoolAPI.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstMidName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Instructor");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstMidName = "Son Kim Quang",
                            HireDate = new DateTime(2021, 8, 18, 12, 0, 29, 350, DateTimeKind.Local).AddTicks(6067),
                            LastName = "Thach"
                        },
                        new
                        {
                            ID = 2,
                            FirstMidName = "Ngoc Tam",
                            HireDate = new DateTime(2021, 8, 18, 12, 0, 29, 350, DateTimeKind.Local).AddTicks(6792),
                            LastName = "Vo"
                        },
                        new
                        {
                            ID = 3,
                            FirstMidName = "Van A",
                            HireDate = new DateTime(2021, 8, 18, 12, 0, 29, 350, DateTimeKind.Local).AddTicks(6796),
                            LastName = "Nguyen"
                        },
                        new
                        {
                            ID = 4,
                            FirstMidName = "Thoai",
                            HireDate = new DateTime(2021, 8, 18, 12, 0, 29, 350, DateTimeKind.Local).AddTicks(6797),
                            LastName = "Chi"
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.OfficeAssignment", b =>
                {
                    b.Property<int>("InstructorID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InstructorID");

                    b.ToTable("OfficeAssignment");
                });

            modelBuilder.Entity("SchoolAPI.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstMidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EnrollmentDate = new DateTime(2021, 8, 18, 12, 0, 29, 348, DateTimeKind.Local).AddTicks(9116),
                            FirstMidName = "Nhat Nam",
                            LastName = "Hoang"
                        },
                        new
                        {
                            ID = 2,
                            EnrollmentDate = new DateTime(2021, 8, 18, 12, 0, 29, 349, DateTimeKind.Local).AddTicks(6801),
                            FirstMidName = "Nhat Minh",
                            LastName = "Thi"
                        },
                        new
                        {
                            ID = 3,
                            EnrollmentDate = new DateTime(2021, 8, 18, 12, 0, 29, 349, DateTimeKind.Local).AddTicks(6815),
                            FirstMidName = "Viet Hung",
                            LastName = "Ngo"
                        },
                        new
                        {
                            ID = 4,
                            EnrollmentDate = new DateTime(2021, 8, 18, 12, 0, 29, 349, DateTimeKind.Local).AddTicks(6817),
                            FirstMidName = "Duc Thai",
                            LastName = "Luu"
                        });
                });

            modelBuilder.Entity("SchoolAPI.Models.Enrollment", b =>
                {
                    b.HasOne("SchoolAPI.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAPI.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolAPI.Models.OfficeAssignment", b =>
                {
                    b.HasOne("SchoolAPI.Models.Instructor", "Instructor")
                        .WithOne("OfficeAssignment")
                        .HasForeignKey("SchoolAPI.Models.OfficeAssignment", "InstructorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SchoolAPI.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolAPI.Models.Instructor", b =>
                {
                    b.Navigation("OfficeAssignment");
                });

            modelBuilder.Entity("SchoolAPI.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
